version: '3'

services:
  selenium:
    build:
      context: ./selenium
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_INSTANCES=1
      - SE_NODE_MAX_SESSION=1
    networks:
      - selenium_network

  python-app:
    build:
      context: ./python-app
    environment:
      - MyEntergy_USERNAME=${MyEntergy_USERNAME}
      - MyEntergy_PASSWORD=${MyEntergy_PASSWORD}
      - MyEntergy_TIMEOUT=${MyEntergy_TIMEOUT}
      - MyEntergy_DEBUG=${MyEntergy_DEBUG}
      - mqtt_host=${MQTT_HOST}
      - mqtt_port=${MQTT_PORT}
      - mqtt_user=${MQTT_USER}
      - mqtt_password=${MQTT_PASSWORD}
      - mqtt_topic=${MQTT_TOPIC}
    depends_on:
      - selenium
    networks:
      - selenium_network

networks:
  selenium_network:
    driver: bridge
