apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: python-app
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: python-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: python-app
    spec:
      containers:
        - env:
            - name: MyEntergy_DEBUG
            - name: MyEntergy_PASSWORD
            - name: MyEntergy_TIMEOUT
            - name: MyEntergy_USERNAME
            - name: mqtt_host
            - name: mqtt_password
            - name: mqtt_port
            - name: mqtt_topic
            - name: mqtt_user
          image: python-app
          name: python-app
      restartPolicy: Always
