apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: selenium
  name: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: selenium
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: selenium
    spec:
      containers:
        - env:
            - name: SE_NODE_MAX_INSTANCES
              value: "1"
            - name: SE_NODE_MAX_SESSION
              value: "1"
          image: selenium
          name: selenium
          ports:
            - containerPort: 4444
              protocol: TCP
      restartPolicy: Always
